@host = http://localhost:5000
###
GET {{host}}/gettabledata HTTP/1
Content-Type: application/json

###
POST {{host}}/insertrow HTTP/1
Content-Type: application/json

{
	"name": "carrier test 2",
	"address": "123 fake lane faketown, fakestate 12345",
	"phone_number": "1234567890",
	"taxable": "1",
	"tier_number": "3",
	"two_digit_unique_code": "01"
}

###
PUT {{host}}/updateitem HTTP/1
Content-Type: application/json

{
    "rowID": "13",
	"column": "tier_number",
	"value": "4"
}

###
DELETE {{host}}/deleterow HTTP/1
Content-Type: application/json

{
	"id": "12"
}
