@host_server = http://172.20.13.129:8943

# 33 = voxbeam, 34 = PNG
@test_carrier_id = 33 
@test_tier = 'standard'

###
POST /toCarrier/{toCarrierId}/tier/{tier}/profile
{
  "rateMarkup": 1.05,
  "fromCarrierList" : [ {
     "iso": "AF", 
     "fromCarrier" : [{"fromCarrierId": 36, "rateCardTier": "carrier36_tier"}]
    }
  ],
  "customRateList" :[ {
     "iso": "AF", 
     "finalRate" : 1.29,
     "minRate" : 1.21
    }
  ]
}


###
GET /toCarrier/{toCarrierId}/tier/{tier}/profile

response body:
{
  CustomerCarrierName,
  RateMarkup,
  fromCarrierList: [ {iso: AF, 
     fromCarrier: [{fromCarrierId, rateCardTier}]
    }
  ],
  customRateList:[ {
     iso: AF, 
     finalRate,
     minRate
    }
  ]
}

###
GET /fromCarrier/{fromCarrierId}/tier/{ratecardTier}/ratecards

response body:
{
	"ratecards": [{
		"ratecardId",
		"ratecardName",
		"start_ts",
		"end_ts",
		"add_ts"
	   }
	]
}

###
GET /fromCarrier/{fromCarrierId}/ratecard/{ratecardId}

response body:

{
	"AF" : [ {
  	  "id" : 6,
  	  "prefix" : "93",
  	  "destination" : "AFGHANISTAN",
 	  "buy_rate" : 0.125,
  	  "buy_rate_minimum" :1,
  	  "buy_rate_increment" : 1,
	  "start_ts" : long,
  	  "end_ts" : long
	 }, {
  	  "id" : 6,
  	  "prefix" : "9370",
  	  "destination" : "AFGHANISTAN MOBILE AWCC",
  	  "buy_rate" : 0.125,
  	  "buy_rate_minimum" :1,
  	  "buy_rate_increment" : 1,
	  "start_ts" : long,
  	  "end_ts" : long
 	 }
	]
}


###
GET /toCarrier/{toCarrierId}/tier/{tier}/price?limit=N (N=1,2,...)
# (give first N records from the customer_carrier_profile_price table (table 4 below),
# latest record first.  The default N=1, means if no 'limit=N' given, 
# you will the latest record)
# result body will be:
# { 
#   "price" : 
#   [ {
#     "time" : mmddyyyy:HH:MM:SS
#     "rates" : {
#       "AF" : [ {
# 	"id" : 6,
#         "start_ts" : 1511668130000,
#         "end_ts" : 1511968130000,
#         "prefix" : "93",
#         "sell_rate_minimum" : 1,
#         "buy_rate_minimum" : 1,
#         "destination" : "AFGHANISTAN",
#         "buy_rate_increment" : 1,
#         "sell_rate" : 0.125,
#         "buy_rate" : 0.125,
#         "sell_rate_increment" : 1
#       }, {
# 	"id" : 6,
#         "start_ts" : 1511868130000,
#         "end_ts" : 1512868130000,
#         "prefix" : "9370",
#         "sell_rate_minimum" : 1,
#         "buy_rate_minimum" : 1,
#         "destination" : "AFGHANISTAN MOBILE AWCC",
#         "buy_rate_increment" : 1,
#         "sell_rate" : 0.125,
#         "buy_rate" : 0.125,
#         "sell_rate_increment" : 1
#       } ]
#     },
#     "profile" : {
#       "rateMarkup" : 1.25,
#       "customRateList" : [ {
#         "iso" : "AF",
#         "minRate" : 1.21,
#         "finalRate" : 1.29
#       }, {
#         "iso" : "US",
#         "minRate" : 0.19,
#         "finalRate" : 0.39
#       }, {
#         "iso" : "CN",
#         "minRate" : 0.29,
#         "finalRate" : 0.59
#       } ],
#       "fromCarrierList" : [ {
#         "iso" : "AF",
#         "fromCarrier" : [ {
#           "rateCardTier" : "carrier36_tier",
#           "fromCarrierId" : 36
#         }, {
#           "rateCardTier" : "carrier33_tier",
#           "fromCarrierId" : 33
#         }, {
#           "rateCardTier" : "carrier35_tier",
#           "fromCarrierId" : 35
#         } ]
#       } ]
#     }
#   }, {
#     "time" : mmddyyyy:HH:MM:SS
#     "rates" : {
#       "AF" : [ {
#         "start_ts" : 1511668130000,
#         "end_ts" : 1511968130000,
#         "prefix" : "93",
#         "sell_rate_minimum" : 1,
#         "buy_rate_minimum" : 1,
#         "destination" : "AFGHANISTAN",
#         "buy_rate_increment" : 1,
#         "sell_rate" : 0.125,
#         "buy_rate" : 0.125,
#         "sell_rate_increment" : 1
#       }, {
#         "start_ts" : 1511868130000,
#         "end_ts" : 1512868130000,
#         "prefix" : "9370",
#         "sell_rate_minimum" : 1,
#         "buy_rate_minimum" : 1,
#         "destination" : "AFGHANISTAN MOBILE AWCC",
#         "buy_rate_increment" : 1,
#         "id" : 6,
#         "sell_rate" : 0.125,
#         "buy_rate" : 0.125,
#         "sell_rate_increment" : 1
#       } ]
#     },
#     "profile" : {
#       "rateMarkup" : 1.25,
#       "customRateList" : [ {
#         "iso" : "AF",
#         "minRate" : 1.21,
#         "finalRate" : 1.29
#       }, {
#         "iso" : "US",
#         "minRate" : 0.19,
#         "finalRate" : 0.39
#       }, {
#         "iso" : "CN",
#         "minRate" : 0.29,
#         "finalRate" : 0.59
#       } ],
#       "fromCarrierList" : [ {
#         "iso" : "AF",
#         "fromCarrier" : [ {
#           "rateCardTier" : "carrier36_tier",
#           "fromCarrierId" : 36
#         }, {
#           "rateCardTier" : "carrier33_tier",
#           "fromCarrierId" : 33
#         }, {
#           "rateCardTier" : "carrier35_tier",
#           "fromCarrierId" : 35
#         } ]
#       } ]
#     }
#   } ]
# }

###
POST /toCarrier/{toCarrierId}/tier/{tier}/price

{
  "profile": {
	rateMarkup,
  	fromCarrierList: [ {
     		iso: AF, 
     		fromCarrier: [{fromCarrierId, rateCardTier}]
        }
      ],
  	customRateList:[ {
     		iso: AF, 
     		finalRate,
     		minRate
    		}
  	   ],
  },
  "rates":{
     "AU" : [ {
	   "id" : 5,
  	   "prefix" : "93",
  	   "destination" : "AFGHANISTAN",
 	   "buy_rate" : 0.125,
  	   "buy_rate_minimum" :1,
  	   "buy_rate_increment" : 1,
 	   "sell_rate" : 0.125,
  	   "sell_rate_minimum" :1,
  	   "sell_rate_increment" : 1,
	   "start_ts" : long,
  	   "end_ts" : long	 
	 }, 
	 {
  	   "id" : 6,
  	   "prefix" : "9370",
  	   "destination" : "AFGHANISTAN MOBILE AWCC",
  	   "buy_rate" : 0.125,
  	   "buy_rate_minimum" :1,
  	   "buy_rate_increment" : 1,
 	   "sell_rate" : 0.125,
  	   "sell_rate_minimum" :1,
  	   "sell_rate_increment" : 1,
	   "start_ts" : long,
  	   "end_ts" : long
 	 }
      ]
   }
}

# DB Tables：
# ==========
# 1. customer_carrier_profile:
# id, 	    	   	<== auto gen
# customer_carrier_id,  	<== POST input: Customer
# tier,	        	<== POST input: Tier
# ts,	        	<== current timestamp
# markup	   		<== POST input: rate_markup

# 2. customer_from_carrierlist
# id, 			<== auto gen
# profile_id,		<== foreign key of customer_carrier_profile.id 
# country_iso, 		<== POST input: fromCarrierList.iso
# from_carrier_id, 	<== POST input: fromCarrierList.fromCarrierId
# ratecard_tier		<== POST input: fromCarrierList.rateCardTier

# 3. customer_carrier_profile_rate
# id, 		<== auto gen
# profile_id,	<== foreign key of customer_carrier_profile.id 
# country_iso, 	<== POST input: customRateList.iso
# final_rate,	<== POST input: customRateList.finalRate
# min_rate	<== POST input: customRateList.minRate

# 4. customer_carrier_profile_price
# id, 		<== auto gen
# profile_id, 	<== foreign key of customer_carrier_profile.id
# ts,		<== current timestamp 
# price (Json)	<== POST input: price


# price:
# {
#   [
#     {"profile": {...}, "rates": {...}}, （whole body of POST /toCarrier/{toCarrierId}/tier/{tier}/rates - see above)
#     ...,
#     {...}
#   ]
# }
