
@host_server = https://api.obie-x.com/obietel

@X-Application-ID = BF3E86D03C63053271B1E6C8582464D4
@X-Device-ID = web


##dynamic token and account id got from the first api
@Authorization_ADMIN = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJHbG9iaWUiLCJpc3MiOiJPYmllVGVsIiwiZXhwIjoxNTM1NjM4OTIzLCJhaWQiOiJCRjNFODZEMDNDNjMwNTMyNzFCMUU2Qzg1ODI0NjRENCIsImRpZCI6IndlYiIsInN0eXAiOjUwLCJzaWQiOjUxMTl9.p8p7IzJ56ABNACIUNyaBLi_KQubm-xL53d8iXcz_qy0
@account_id = 5119
# 5119 Wenyun

#### auth manager 
POST {{host_server}}/auth
X-Application-ID: {{X-Application-ID}}
X-Device-ID: {{X-Device-ID}}
Content-Type: application/json

{
    "subscriber_login": "19143493981",
    "subscriber_password": "scorpio1988",
     "devicemeta": {
        "language": "en",
        "os_name": "android",
        "os_version": "string"
    }
}

### get subscriber check subscriber info
GET {{host_server}}/subscriber/{{account_id}} HTTP/1.1
Content-Type: application/json 
X-Application-ID: {{X-Application-ID}}
X-Device-ID: {{X-Device-ID}} 
Authorization: Bearer {{Authorization_ADMIN}}